import * as T from 'three';
import {clone} from './skeleton-utils.js';
export const enemyTypes=[{file:'imported-zombie_walk_test',name:'الزاحف',height:1.85,speed:1.5},{file:'imported-zombie_scream',name:'الصارخ',height:1.9,speed:1.8},{file:'imported-crying_head',name:'الرأس العنكبوتي',height:1.35,speed:2.3},{file:'imported-dark_knight_01',name:'الفارس المظلم',height:2.05,speed:1.2},{file:'imported-midpoly',name:'الحارس المدرع',height:2.15,speed:1.1}];
export async function loadEnemyLibrary(loader,zombiesOnly=false){const sources=await Promise.all(enemyTypes.map((t,i)=>zombiesOnly&&i>1?null:loader.loadAsync('./assets/'+t.file+'.glb')));const sword=zombiesOnly?null:await loader.loadAsync('./assets/imported-katana.glb');for(let i=0;i<sources.length;i++){const source=sources[i],remove=[];if(!source)continue;source.scene.traverse(o=>{if(o.isMesh&&/floor/i.test(o.name))remove.push(o)});remove.forEach(o=>o.removeFromParent());const mixer=new T.AnimationMixer(source.scene),clip=source.animations.find(c=>/idle|walk|animation zombie/i.test(c.name))||source.animations[0];if(clip){mixer.clipAction(clip).play();mixer.update(.01)}source.scene.updateMatrixWorld(true);const box=new T.Box3().setFromObject(source.scene,true),center=box.getCenter(new T.Vector3());source.fit={scale:enemyTypes[i].height/box.getSize(new T.Vector3()).y,minY:box.min.y,center};mixer.stopAllAction()};return{sources,sword}}
export function buildEnemy(library,index,boss){const typeIndex=boss?3:index%enemyTypes.length,type=enemyTypes[typeIndex],template=library.sources[typeIndex],model=clone(template.scene),pose=new T.Group(),group=new T.Group();pose.add(model);group.add(pose);const fit=template.fit,scale=fit.scale*(boss?1.2:1);model.scale.multiplyScalar(scale);model.position.add(new T.Vector3(-fit.center.x*scale,-fit.minY*scale,-fit.center.z*scale));const bones=[];model.traverse(o=>{if(o.isBone)bones.push({bone:o,base:o.quaternion.clone()});if(o.isMesh){o.castShadow=true;o.receiveShadow=true;const old=Array.isArray(o.material)?o.material:[o.material],mats=old.map(m=>{const copy=m.clone();if(typeIndex===4){copy.color.set(/Armor/.test(m.name)?0x737f8c:/Cloth/.test(m.name)?0x423d39:0x252b32);copy.metalness=/Armor/.test(m.name)?.65:.1;copy.roughness=.55}return copy});o.material=Array.isArray(o.material)?mats:mats[0]}});
const mixer=new T.AnimationMixer(model),actions={},find=(pattern)=>template.animations.find(c=>pattern.test(c.name));const move=find(/walk|animation zombie|^move$|run/i),idle=find(/idle/i)||move||template.animations[0];const clips={Idle:idle,Walk:move||idle,Run_Arms:move||idle,Punch:find(/punch|attack|mixamo/i),Death:find(/death/i),HitReact:find(/hitreact/i)};for(const [name,clip]of Object.entries(clips)){if(!clip)continue;const action=mixer.clipAction(clip.clone());if(['Death','Punch','HitReact'].includes(name)){action.setLoop(T.LoopOnce,1);action.clampWhenFinished=true}actions[name]=action}
let sword;if(typeIndex===3){sword=new T.Group();const blade=library.sword.scene.clone(true),bb=new T.Box3().setFromObject(blade),size=bb.getSize(new T.Vector3()),ss=1.1/Math.max(size.x,size.y,size.z);blade.scale.multiplyScalar(ss);const center=bb.getCenter(new T.Vector3());blade.position.addScaledVector(center,-ss);sword.add(blade);sword.position.set(-.48,1.02,.13);sword.rotation.z=-.85;pose.add(sword)}
return{group,pose,model,mixer,actions,bones,sword,typeIndex,kind:type.name,height:type.height*(boss?1.2:1),speed:type.speed,boss,phase:index*.7};}
const axisX=new T.Vector3(1,0,0),rotation=new T.Quaternion();
export function updateEnemyVisual(e,dt){
 e.phase+=dt*(e.moving?e.speed*3.2:1.4);
 if(e.dead){const t=Math.min(1,(3-e.deathTime)/.85),ease=t*t*(3-2*t);if(!e.actions.Death){e.pose.rotation.x=-ease*Math.PI*.47;e.pose.rotation.z=Math.sin(t*Math.PI)*.12;e.pose.position.y=-ease*.22}if(e.deathTime<.8)e.pose.position.y-=dt*.65;return}
 const progress=e.attackTimer>0?1-e.attackTimer/e.attackDuration:0,contact=e.windup/e.attackDuration;
 const strike=progress<contact?-.4*Math.sin(progress/contact*Math.PI/2):Math.sin(Math.min(1,(progress-contact)/(1-contact))*Math.PI)*.95;
 e.pose.rotation.x=e.stagger>0?.16:e.attackTimer>0?strike*.22:e.moving?.035:0;
 e.pose.rotation.z=e.moving?Math.sin(e.phase)*.018:0;
 e.pose.position.y=e.moving?Math.abs(Math.sin(e.phase))*(e.typeIndex===2?.045:.018):Math.sin(e.phase)*.007;
 if(e.sword){e.sword.rotation.z=-.85+strike*2.1;e.sword.rotation.x=strike*.6}
 for(const {bone,base}of e.bones){const n=bone.name.toLowerCase();let angle=0;
 if(e.typeIndex===4){bone.quaternion.copy(base);const side=/_l$/.test(n)?1:-1;if(/^(thigh|upperarm)_[lr]$/.test(n)&&e.moving)angle=Math.sin(e.phase)*(/thigh/.test(n)?.38:-.24)*side;if(/^calf_[lr]$/.test(n)&&e.moving)angle=Math.max(0,Math.sin(e.phase)*side)*.42;if(/spine_01/.test(n))angle=.08;}
 if(e.attackTimer>0&&!e.actions.Punch){if(/upperarm|arm_l|arm_r|leftarm|rightarm/.test(n)&&!/fore|lower/.test(n))angle+=strike*1.05;if(/spine/.test(n))angle+=strike*.025;}
 if(e.stagger>0&&/spine/.test(n))angle+=.045;
 if(angle)bone.quaternion.multiply(rotation.setFromAxisAngle(axisX,angle));
 }
}
