import * as T from 'three';
import {clone} from './skeleton-utils.js';
export const enemyTypes=[{file:'imported-zombie_walk_test',name:'الزاحف',height:1.85,speed:1.5},{file:'imported-zombie_scream',name:'الصارخ',height:1.9,speed:1.8},{file:'imported-crying_head',name:'الرأس العنكبوتي',height:1.35,speed:2.3},{file:'imported-dark_knight_01',name:'الفارس المظلم',height:2.05,speed:1.2},{file:'imported-midpoly',name:'الحارس المدرع',height:2.15,speed:1.1}];
export async function loadEnemyLibrary(loader){const sources=await Promise.all(enemyTypes.map(t=>loader.loadAsync('./assets/'+t.file+'.glb')));const sword=await loader.loadAsync('./assets/imported-katana.glb');for(let i=0;i<sources.length;i++){const source=sources[i],remove=[];source.scene.traverse(o=>{if(o.isMesh&&/floor/i.test(o.name))remove.push(o)});remove.forEach(o=>o.removeFromParent());const mixer=new T.AnimationMixer(source.scene),clip=source.animations.find(c=>/idle|walk|animation zombie/i.test(c.name))||source.animations[0];if(clip){mixer.clipAction(clip).play();mixer.update(.01)}source.scene.updateMatrixWorld(true);const box=new T.Box3().setFromObject(source.scene,true),center=box.getCenter(new T.Vector3());source.fit={scale:enemyTypes[i].height/box.getSize(new T.Vector3()).y,minY:box.min.y,center};mixer.stopAllAction()};return{sources,sword}}
export function buildEnemy(library,index,boss){const typeIndex=boss?3:index%enemyTypes.length,type=enemyTypes[typeIndex],template=library.sources[typeIndex],model=clone(template.scene),pose=new T.Group(),group=new T.Group();pose.add(model);group.add(pose);const fit=template.fit,scale=fit.scale*(boss?1.2:1);model.scale.multiplyScalar(scale);model.position.add(new T.Vector3(-fit.center.x*scale,-fit.minY*scale,-fit.center.z*scale));const bones=[];model.traverse(o=>{if(o.isBone)bones.push({bone:o,base:o.quaternion.clone()});if(o.isMesh){o.castShadow=true;o.receiveShadow=true;const old=Array.isArray(o.material)?o.material:[o.material],mats=old.map(m=>{const copy=m.clone();if(typeIndex===4){copy.color.set(/Armor/.test(m.name)?0x737f8c:/Cloth/.test(m.name)?0x423d39:0x252b32);copy.metalness=/Armor/.test(m.name)?.65:.1;copy.roughness=.55}return copy});o.material=Array.isArray(o.material)?mats:mats[0]}});
const mixer=new T.AnimationMixer(model),actions={},find=(pattern)=>template.animations.find(c=>pattern.test(c.name));const move=find(/walk|animation zombie|^move$|run/i),idle=find(/idle/i)||move||template.animations[0];const clips={Idle:idle,Walk:move||idle,Run_Arms:move||idle,Punch:find(/punch|attack|mixamo/i),Death:find(/death/i),HitReact:find(/hitreact/i)};for(const [name,clip]of Object.entries(clips)){if(!clip)continue;const action=mixer.clipAction(clip.clone());if(['Death','Punch','HitReact'].includes(name)){action.setLoop(T.LoopOnce,1);action.clampWhenFinished=true}actions[name]=action}
let sword;if(typeIndex===3){sword=new T.Group();const blade=library.sword.scene.clone(true),bb=new T.Box3().setFromObject(blade),size=bb.getSize(new T.Vector3()),ss=1.1/Math.max(size.x,size.y,size.z);blade.scale.multiplyScalar(ss);const center=bb.getCenter(new T.Vector3());blade.position.addScaledVector(center,-ss);sword.add(blade);sword.position.set(-.48,1.02,.13);sword.rotation.z=-.85;pose.add(sword)}
return{group,pose,model,mixer,actions,bones,sword,typeIndex,kind:type.name,height:type.height*(boss?1.2:1),speed:type.speed,boss,phase:index*.7};}
export function updateEnemyVisual(e,dt){e.phase+=dt*4;if(e.dead){if(!e.actions.Death){const t=Math.min(1,(3-e.deathTime)/.7);e.pose.rotation.x=-t*Math.PI*.48;e.pose.position.y=-t*.35}return}e.pose.rotation.x=e.attackTimer>0?-Math.sin(e.attackTimer/.75*Math.PI)*.15:e.stagger>0?.13:0;e.pose.position.y=e.attackTimer>0?0:Math.sin(e.phase)*.016;if(e.sword)e.sword.rotation.z=-.85+Math.sin(Math.max(0,e.attackTimer)/.75*Math.PI)*1.7;
if(e.typeIndex===4){for(const {bone,base}of e.bones){let angle=0;const name=bone.name;if(/^(thigh|upperarm)_[lr]$/.test(name)){const sign=name.endsWith('_l')?1:-1;angle=Math.sin(e.phase)*(/thigh/.test(name)?.25:-.18)*sign;if(/upperarm/.test(name)&&e.attackTimer>0)angle-=Math.sin(e.attackTimer/.75*Math.PI)*.8}bone.quaternion.copy(base).multiply(new T.Quaternion().setFromAxisAngle(new T.Vector3(1,0,0),angle))}}}
