import * as THREE from 'three';
import {GLTFLoader} from './gltf-loader.js';
import {clone as cloneSkeleton} from './skeleton-utils.js';
const $=id=>document.getElementById(id),TAU=Math.PI*2;
const scene=new THREE.Scene();scene.fog=new THREE.Fog(0x9fc2ca,22,85);
const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.07,125);camera.rotation.order='YXZ';
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.42;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;$('world').appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xe8f3ff,0x60727a,2.1));const sun=new THREE.DirectionalLight(0xffe1b2,2.6);sun.position.set(-20,35,18);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-42,right:42,top:42,bottom:-42});sun.shadow.bias=-.0001;scene.add(sun);
const world=new THREE.Group();scene.add(world);const weaponMount=new THREE.Group();camera.add(weaponMount);scene.add(camera);const loader=new GLTFLoader();
const sourceFiles=['zombie'];let source=[];try{source=await Promise.all(sourceFiles.map(id=>loader.loadAsync(`./assets/${id}.glb`)))}catch(e){$('loading').textContent='تعذّر تحميل نماذج الشخصيات. حدّث الصفحة للمحاولة.';throw e}
const rigSources=await Promise.all(['fps-pistol','fps-rifle'].map(id=>loader.loadAsync('./assets/'+id+'.glb')));
$('loading').hidden=true;
const colors=[{name:'قرية الصباح',sky:0x8ec5dc,fog:0xa9c8c2,ground:0x7f9f87,road:0xa9aaa0,wall:0xd9c7aa,roof:0xb97362},{name:'ميناء الغروب',sky:0xe6a979,fog:0xd8b59a,ground:0x8d9c9a,road:0x8f9191,wall:0xc9b4a1,roof:0x607d87},{name:'مدينة النيون',sky:0x4d618e,fog:0x7282a5,ground:0x647981,road:0x575f72,wall:0x7d8391,roof:0x3d5068},{name:'وادي الرمال',sky:0xe8bd83,fog:0xd8bd91,ground:0xc1ae82,road:0xbca987,wall:0xcdb08a,roof:0x97755f},{name:'غابة الجليد',sky:0xaccbd7,fog:0xc1dce1,ground:0xa7c5bd,road:0x8fabb0,wall:0xbacac9,roof:0x75899a}];
let seed=1;function rng(){seed=(seed*16807)%2147483647;return(seed-1)/2147483646}
function material(c){return new THREE.MeshStandardMaterial({color:c,roughness:.86,flatShading:false})}
function add(g,c,x,y,z,parent=world){const m=new THREE.Mesh(g,typeof c==='number'?material(c):c);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function box(x,y,z,w,h,d,c,p=world){return add(new THREE.BoxGeometry(w,h,d),c,x,y,z,p)}
function blob(x,y,z,r,c,p=world){const m=add(new THREE.IcosahedronGeometry(r,2),c,x,y,z,p);return m}
let obstacles=[],enemies=[],effects=[],round=1,kills=0,roundTotal=0,score=0,hp=100,ammo=0,reserve=0,gun,gunGroup,playing=false,transition=0,dead=false,yaw=0,pitch=0,shotClock=0,recoil=0,reloadClock=0,walkPhase=0,jumpVelocity=0,playerY=1.68,fallV=0,movingSpeed=0,hitFlash=0,roundSeed=1;const player=new THREE.Vector3(0,0,14),keys=new Set();let modelsReady=true,gunSwayX=0,gunSwayY=0,audioCtx=null,noiseBuffer=null;
function clearWorld(){for(const child of [...world.children])world.remove(child);obstacles=[];for(const e of enemies)e.mixer?.stopAllAction();enemies=[];effects=[]}
function block(x,z,w,d,h,c){box(x,h/2,z,w,h,d,c);obstacles.push({x,z,w:w/2+.35,d:d/2+.35})}
function makeMap(level){clearWorld();seed=level*7919+173;roundSeed=seed;const theme=colors[(level-1)%colors.length];renderer.setClearColor(theme.sky);scene.fog.color.setHex(theme.fog);sun.color.setHex(level%5===3?0xa9ceff:0xffe5b8);sun.intensity=level%5===3?1.7:2.5;renderer.shadowMap.needsUpdate=true;
box(0,-.38,-10,90,.72,100,theme.ground);box(0,.015,-10,12,.04,82,theme.road);for(const x of [-6.2,6.2])box(x,.025,-10,.14,.05,82,0xe5ddc7);for(let z=24;z>-49;z-=6)box(0,.043,z,.12,.025,2,0xf7efda);
for(let side of [-1,1])for(let i=0;i<7;i++){const z=26-i*11+(rng()-.5)*3,x=side*(11+rng()*6),w=4+rng()*3,d=4+rng()*2,h=3+rng()*3;block(x,z,w,d,h,theme.wall);const roof=add(new THREE.ConeGeometry(Math.max(w,d)*.72,1.5,4),theme.roof,x,h+.7,z);roof.rotation.y=Math.PI/4;for(const dx of [-w*.25,w*.25]){box(x+dx,1.8,z+side*d/2+.06,.8,.95,.12,0x466876);box(x+dx,1.8,z-side*d/2-.06,.8,.95,.12,0x466876)}box(x,h*.35,z+side*d/2+.07,.9,1.8,.12,0x716e67);}
for(let i=0;i<26;i++){let x=(rng()>.5?1:-1)*(18+rng()*23),z=rng()*90-55;if(i%3===0){box(x,2,z,.33,4,.33,0x786c5d);for(let j=0;j<5;j++){const a=j*TAU/5;const b=blob(x+Math.cos(a)*1.3,4+rng(),z+Math.sin(a)*1.3,1.65,[0x46817a,0x519483,0x397367][i%3]);b.scale.y=.85}}else{const b=blob(x,0,z,2+rng()*3,theme.ground);b.scale.y=.5}}
for(let i=0;i<8;i++){let z=18-i*8,x=(rng()>.5?1:-1)*(7.1+rng()*2);block(x,z,1.7,1.5,1.25,i%2?0x84918e:0xa19b89)}
for(let side of [-1,1])for(let i=0;i<6;i++){let z=22-i*12;box(side*7.1,2.6,z,.12,5.2,.12,0x667675);box(side*6.8,5.25,z,.65,.13,.25,0xf1e0b7)}
}
const gunFamilies=[{type:'مسدس',prefix:'FALCON',damage:22,rate:.29,mag:14,spread:.014,range:44,pellets:1},{type:'رشاش خفيف',prefix:'RAVEN',damage:13,rate:.105,mag:32,spread:.045,range:36,pellets:1},{type:'بندقية هجومية',prefix:'VORTEX',damage:19,rate:.155,mag:28,spread:.024,range:60,pellets:1},{type:'شوزن',prefix:'THUNDER',damage:11,rate:.62,mag:9,spread:.09,range:24,pellets:7},{type:'قناص',prefix:'ECLIPSE',damage:65,rate:.88,mag:6,spread:.004,range:90,pellets:1}];
function gunFor(level){const family=gunFamilies[(level-1)%5],tier=Math.floor((level-1)/5)+1,hue=((level*137.508)%360)/360;return {...family,tier,level,name:`${family.prefix} ${String(level).padStart(3,'0')}`,color:new THREE.Color().setHSL(hue,.46,.43),damage:family.damage+Math.floor(tier*1.35),rate:Math.max(.075,family.rate*(1-tier*.008)),mag:family.mag+Math.floor(tier/4),range:family.range+Math.min(18,tier*.5),spread:Math.max(.002,family.spread*(1-tier*.01))}}
function makeWeapon(level){gun=gunFor(level);if(gunGroup){gunGroup.userData.mixer?.stopAllAction();weaponMount.remove(gunGroup)}gunGroup=new THREE.Group();weaponMount.add(gunGroup);gunGroup.position.set(.23,-.34,-.8);
const pistol=(level-1)%5===0,template=rigSources[pistol?0:1],model=cloneSkeleton(template.scene);model.scale.setScalar(pistol?.085:.059);model.rotation.y=Math.PI/2;gunGroup.add(model);
model.traverse(o=>{if(o.isMesh){o.frustumCulled=false;o.castShadow=false;const materials=Array.isArray(o.material)?o.material:[o.material];const copy=materials.map(old=>{const m=old.clone();if(/Wood|Shirt|Frame|DarkPlastic/.test(m.name))m.color.lerp(gun.color,.14);m.roughness=/Metal|Slide/.test(m.name)?.4:.78;return m});o.material=Array.isArray(o.material)?copy:copy[0]}});
const mixer=new THREE.AnimationMixer(model),actions={};for(const name of ['Idle','Shoot','Reload']){const clip=template.animations.find(c=>c.name.endsWith('|'+name));if(clip){actions[name]=mixer.clipAction(clip);if(name!=='Idle'){actions[name].setLoop(THREE.LoopOnce,1);actions[name].clampWhenFinished=true}}}actions.Idle.play();mixer.update(.1);mixer.addEventListener('finished',()=>{if(gunGroup?.userData.mixer!==mixer)return;for(const name of ['Shoot','Reload'])actions[name].fadeOut(.09);actions.Idle.reset().fadeIn(.09).play()});
const muzzle=add(new THREE.SphereGeometry(.06,12,8),new THREE.MeshBasicMaterial({color:0xffdb8b,transparent:true,opacity:0,blending:THREE.AdditiveBlending,depthWrite:false}),.03,.12,pistol?-.37:-.67,gunGroup);muzzle.scale.set(.8,.8,2.2);gunGroup.userData={muzzle,mixer,actions,model,length:pistol?.4:.7};
ammo=gun.mag;reserve=gun.mag*8;reloadClock=shotClock=0;recoil=0;$('gun-type').textContent=gun.type+' · المستوى '+gun.tier;$('gun-name').textContent=gun.name;$('gun-traits').textContent='قوة '+gun.damage+' · سرعة '+Math.round(60/gun.rate);hud()}
function weaponAnimation(name){const actions=gunGroup.userData.actions,action=actions[name];if(!action)return;for(const other of Object.values(actions))if(other!==action)other.fadeOut(.05);action.reset().setEffectiveWeight(1).setEffectiveTimeScale(name==='Shoot'?Math.max(1,action.getClip().duration/gun.rate):1).fadeIn(.025).play()}
function hud(){$('round').textContent=String(round).padStart(2,'0');$('remaining').textContent=Math.max(0,enemies.filter(e=>!e.dead).length);$('score').textContent=score;$('health-text').textContent=Math.max(0,Math.ceil(hp));$('health-fill').style.width=Math.max(0,hp)+'%';$('ammo').textContent=ammo;$('reserve').textContent=reserve}
function toast(t){$('wave-toast').textContent=t;$('wave-toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('wave-toast').classList.remove('show'),1900)}
function makeEnemy(x,z,index,boss){const template=source[0],model=cloneSkeleton(template.scene),group=new THREE.Group();group.position.set(x,0,z);group.add(model);model.scale.setScalar(boss?2.05:1.45+(index%3)*.07);model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.frustumCulled=false;o.material=o.material.clone();o.material.color.set(boss?0xb6aaa0:[0xffffff,0xd0dfca,0xc5ccbb][index%3])}});world.add(group);const mixer=new THREE.AnimationMixer(model),actions={};for(const name of ['Idle','Run_Arms','Walk','HitReact','Death','Punch']){const clip=template.animations.find(c=>c.name===name);if(clip){actions[name]=mixer.clipAction(clip);if(['Death','Punch','HitReact'].includes(name)){actions[name].setLoop(THREE.LoopOnce,1);actions[name].clampWhenFinished=true}}}const e={group,model,mixer,actions,action:null,hp:(boss?260:65)+round*(boss?14:3),maxHp:0,dead:false,boss,cooldown:1.2,attackTimer:0,flash:0,stagger:0,deathTime:0,speed:(boss?1.4:1.3+(index%3)*.35)+Math.min(1.2,round*.012)};e.maxHp=e.hp;animateEnemy(e,'Idle');enemies.push(e);return e}
function animateEnemy(e,name){const next=e.actions[name]||e.actions.Idle;if(!next||e.action===next)return;next.reset().fadeIn(.13).play();if(e.action)e.action.fadeOut(.13);e.action=next}
function spawnRound(level){round=Math.min(100,Math.max(1,level));kills=0;dead=false;transition=0;hp=Math.min(100,hp+28);player.set(0,0,14);playerY=1.68;fallV=0;yaw=0;pitch=0;camera.rotation.set(0,0,0);makeMap(round);makeWeapon(round);const count=Math.min(5+Math.floor(round*.6),18),boss=round%10===0;roundTotal=count+(boss?1:0);for(let i=0;i<count;i++){const x=(rng()-.5)*9,z=8-i*3.5-(rng()*2);makeEnemy(x,z,i+round,false)}if(boss)makeEnemy(0,-45,round+1,true);hud();toast(`الجولة ${round} · ${colors[(round-1)%5].name}${boss?' · زعيم':''}`);try{localStorage.setItem('lasa-round',String(round))}catch{}}
function segmentHitsBox(origin,dir,maxDist,o){let tmin=0,tmax=maxDist;for(const [axis,min,max] of [['x',o.x-o.w,o.x+o.w],['z',o.z-o.d,o.z+o.d]]){let d=dir[axis];if(Math.abs(d)<1e-6){if(origin[axis]<min||origin[axis]>max)return false;continue}let t1=(min-origin[axis])/d,t2=(max-origin[axis])/d;if(t1>t2)[t1,t2]=[t2,t1];tmin=Math.max(tmin,t1);tmax=Math.min(tmax,t2);if(tmin>tmax)return false}return tmin}
function audio(){audioCtx??=new AudioContext();if(audioCtx.state==='suspended')audioCtx.resume();if(!noiseBuffer){noiseBuffer=audioCtx.createBuffer(1,Math.floor(audioCtx.sampleRate*.5),audioCtx.sampleRate);const samples=noiseBuffer.getChannelData(0);for(let i=0;i<samples.length;i++)samples[i]=Math.random()*2-1}return audioCtx}
function noise(t,duration,frequency,volume,filterType='lowpass'){const ctx=audio(),source=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();source.buffer=noiseBuffer;filter.type=filterType;filter.frequency.setValueAtTime(frequency,t);filter.frequency.exponentialRampToValueAtTime(Math.max(120,frequency*.2),t+duration);gain.gain.setValueAtTime(Math.max(.001,volume),t);gain.gain.exponentialRampToValueAtTime(.001,t+duration);source.connect(filter).connect(gain).connect(ctx.destination);source.start(t);source.stop(t+duration)}
function tone(t,freq,end,duration,volume,type='triangle'){const ctx=audio(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,t);osc.frequency.exponentialRampToValueAtTime(Math.max(40,end),t+duration);gain.gain.setValueAtTime(volume,t);gain.gain.exponentialRampToValueAtTime(.001,t+duration);osc.connect(gain).connect(ctx.destination);osc.start(t);osc.stop(t+duration)}
function playShot(){try{const t=audio().currentTime,heavy=gun.type==='قناص'||gun.type==='شوزن',rapid=gun.type==='رشاش خفيف';noise(t,heavy?.39:.24,heavy?1300:2200,heavy?.22:.14);noise(t,.035,heavy?5500:7200,heavy?.18:.12,'highpass');tone(t,heavy?125:rapid?190:160,heavy?43:70,heavy?.25:.16,heavy?.25:.14,'sawtooth');noise(t+.07,heavy?.38:.18,480,heavy?.065:.035);tone(t+.045,960,320,.09,.025,'square')}catch{}}
function playReload(){try{const t=audio().currentTime;noise(t,.06,3100,.055,'highpass');tone(t,480,190,.055,.035,'square');noise(t+.16,.075,2000,.05,'highpass');tone(t+.19,320,140,.085,.045,'triangle')}catch{}}
function playHit(){try{const t=audio().currentTime;tone(t,760,510,.07,.04);noise(t,.045,4800,.035,'highpass')}catch{}}
function tracer(start,end){const points=[start,end];const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:0xffebbf,transparent:true,opacity:.85,depthWrite:false}));scene.add(line);effects.push({m:line,life:.095})}
function casing(){if(!gunGroup)return;gunGroup.updateWorldMatrix(true,false);const pos=gunGroup.localToWorld(new THREE.Vector3(.09,.09,-.18));const m=add(new THREE.CylinderGeometry(.018,.018,.055,12),new THREE.MeshStandardMaterial({color:0xc8a962,metalness:.8,roughness:.3}),pos.x,pos.y,pos.z,scene);m.rotation.z=1.1;effects.push({m,life:.55,velocity:new THREE.Vector3(1.5+Math.random(),1.4,-.4)})}
function shoot(){if(!playing||dead||transition>0||reloadClock>0||shotClock>0)return;if(ammo<=0){reload();return}ammo--;shotClock=gun.rate;recoil=Math.min(.4,recoil+(gun.type==='قناص'?.27:gun.type==='شوزن'?.21:.12));gunGroup.userData.muzzle.material.opacity=1;weaponAnimation('Shoot');playShot();casing();const origin=camera.position.clone(),base=new THREE.Vector3(0,0,-1).applyQuaternion(camera.quaternion);let hit=false;
for(let p=0;p<gun.pellets;p++){const dir=base.clone().add(new THREE.Vector3((Math.random()-.5)*gun.spread,(Math.random()-.5)*gun.spread,(Math.random()-.5)*gun.spread)).normalize();let target=null,best=gun.range;for(const e of enemies){if(e.dead)continue;const center=e.group.position.clone().add(new THREE.Vector3(0,e.boss?1.55:1.13,0)),to=center.clone().sub(origin),proj=to.dot(dir);if(proj<0||proj>best)continue;const radius=e.boss?1.05:.72,perp=to.lengthSq()-proj*proj;if(perp>radius*radius)continue;const depth=proj-Math.sqrt(Math.max(0,radius*radius-perp));if(depth<best){best=depth;target=e}}if(target){let blocked=false;for(const o of obstacles){let d=segmentHitsBox(origin,dir,best,o);if(d!==false&&d<best){blocked=true;break}}if(!blocked){damageEnemy(target,gun.damage);hit=true;impact(origin.clone().addScaledVector(dir,best),0xffe5af)}}if(p===0)tracer(origin.clone().addScaledVector(dir,.7),origin.clone().addScaledVector(dir,Math.min(best,gun.range)));if(!target)impact(origin.clone().addScaledVector(dir,Math.min(22,gun.range)),0xe3f6fb)}
if(hit){playHit();$('hitmarker').style.opacity=1;clearTimeout(shoot.hitTimer);shoot.hitTimer=setTimeout(()=>$('hitmarker').style.opacity=0,95)}hud();if(ammo===0)reload()}
function damageEnemy(e,amount){if(e.dead)return;e.hp-=amount;e.flash=.14;e.stagger=.26;animateEnemy(e,'HitReact');if(e.hp<=0){e.dead=true;e.deathTime=3.0;animateEnemy(e,'Death');score+=e.boss?1000:100;kills++;hud();if(kills>=roundTotal){if(round===100){endGame(true)}else{transition=3.2;toast(`قتلت كل اعداء لاسا · الجولة ${round}`);hp=Math.min(100,hp+12)}}}}
function impact(position,color){const m=add(new THREE.SphereGeometry(.055,6,5),new THREE.MeshBasicMaterial({color,transparent:true}),position.x,position.y,position.z,scene);m.castShadow=false;effects.push({m,life:.24})}
function reload(){if(!playing||dead||reloadClock>0||ammo===gun.mag||reserve<=0)return;reloadClock=gunGroup.userData.actions.Reload.getClip().duration;weaponAnimation('Reload');playReload();toast('جارٍ التلقيم…')}
function endGame(victory){playing=false;dead=!victory;$('overlay').hidden=false;$('overlay-kicker').textContent=victory?'١٠٠ / ١٠٠':'انتهت الجولة';$('overlay-title').textContent=victory?'أكملت المئة جولة!':'حاول من جديد';$('overlay-text').textContent=victory?'كل الجولات انتهت. أصبحت أسطورة لاسا.':`وصلت إلى الجولة ${round}. يمكنك إعادة المحاولة من هذه الجولة.`;$('play').textContent=victory?'ابدأ من الجولة الأولى':'أعد الجولة';if(victory)try{localStorage.setItem('lasa-round','1')}catch{}if(document.pointerLockElement)document.exitPointerLock()}
function collision(pos){pos.x=THREE.MathUtils.clamp(pos.x,-24,24);pos.z=THREE.MathUtils.clamp(pos.z,-48,29);for(const o of obstacles){const dx=pos.x-o.x,dz=pos.z-o.z,ox=o.w+.35-Math.abs(dx),oz=o.d+.35-Math.abs(dz);if(ox>0&&oz>0){if(ox<oz)pos.x+=Math.sign(dx||1)*ox;else pos.z+=Math.sign(dz||1)*oz}}}
const joystick={x:0,y:0,id:null},look={id:null,x:0,y:0};let mobile=matchMedia('(pointer:coarse)').matches;
function loop(now){requestAnimationFrame(loop);const dt=Math.min((now-(loop.prev||now))/1000,.04);loop.prev=now;gunSwayX=THREE.MathUtils.lerp(gunSwayX,0,1-Math.exp(-8*dt));gunSwayY=THREE.MathUtils.lerp(gunSwayY,0,1-Math.exp(-8*dt));if(!modelsReady)return;shotClock=Math.max(0,shotClock-dt);recoil=Math.max(0,recoil-dt*2.4);hitFlash=Math.max(0,hitFlash-dt*3);$('damage-flash').style.opacity=hitFlash*.28;if(gunGroup){gunGroup.userData.muzzle.material.opacity=Math.max(0,gunGroup.userData.muzzle.material.opacity-dt*12)}
if(playing){let mx=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+joystick.x,my=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0)-joystick.y;const d=new THREE.Vector3(Math.sin(yaw)*my+Math.cos(yaw)*mx,0,-Math.cos(yaw)*my+Math.sin(yaw)*mx);if(d.lengthSq()>1)d.normalize();movingSpeed=THREE.MathUtils.lerp(movingSpeed,d.lengthSq()?(keys.has('ShiftLeft')?7.8:5.2):0,1-Math.exp(-13*dt));player.addScaledVector(d,dt*movingSpeed);collision(player);walkPhase+=dt*movingSpeed*2.2;fallV-=16*dt;playerY+=fallV*dt;if(playerY<=1.68){playerY=1.68;fallV=0}camera.position.set(player.x,playerY+Math.sin(walkPhase)*.018*Math.min(1,movingSpeed/5),player.z);camera.rotation.set(pitch,yaw,0,'YXZ');if(keys.has('Mouse0')||keys.has('KeyJ'))shoot();if(keys.has('KeyR'))reload();if(reloadClock>0){reloadClock=Math.max(0,reloadClock-dt);if(reloadClock===0){let taken=Math.min(gun.mag-ammo,reserve);ammo+=taken;reserve-=taken;hud()}}if(transition>0){transition-=dt;if(transition<=0)spawnRound(round+1)}}
if(gunGroup){if(playing)gunGroup.userData.mixer.update(dt);const bob=Math.min(1,movingSpeed/5);gunGroup.position.set(.23+Math.sin(walkPhase)*.009*bob+gunSwayX*.004,-.34+Math.abs(Math.sin(walkPhase))*.009*bob,-.8+recoil*.06);gunGroup.rotation.set(recoil*.10,gunSwayX*.004,gunSwayY*.004)}
for(const e of enemies){if(!playing&&!e.dead)continue;e.mixer.update(dt);if(e.dead){e.deathTime-=dt;if(e.deathTime<0)e.group.visible=false;continue}e.flash=Math.max(0,e.flash-dt);e.stagger=Math.max(0,e.stagger-dt);e.cooldown=Math.max(0,e.cooldown-dt);const dx=player.x-e.group.position.x,dz=player.z-e.group.position.z,dist=Math.hypot(dx,dz);e.group.rotation.y=Math.atan2(dx,dz);if(e.stagger>0){e.attackTimer=0;e.group.position.addScaledVector(new THREE.Vector3(dx,0,dz).normalize(),-dt*1.4);continue}
if(e.attackTimer>0){const before=e.attackTimer;e.attackTimer-=dt;if(before>.36&&e.attackTimer<=.36&&dist<(e.boss?2.1:1.65)){hp=Math.max(0,hp-(e.boss?24:9+Math.min(9,Math.floor(round/12))));hitFlash=.8;hud();if(hp<=0)endGame(false)}if(e.attackTimer<=0){e.cooldown=.65;e.action=null;animateEnemy(e,'Idle')}}else if(dist>(e.boss?1.65:1.25)){e.group.position.x+=dx/dist*dt*e.speed;e.group.position.z+=dz/dist*dt*e.speed;for(const other of enemies){if(other===e||other.dead)continue;const offset=e.group.position.clone().sub(other.group.position);const separation=offset.length();if(separation>0&&separation<.7)e.group.position.addScaledVector(offset,dt*(.7-separation)/separation)}collision(e.group.position);animateEnemy(e,e.speed>2?'Run_Arms':'Walk')}else if(e.cooldown===0){e.attackTimer=.75;e.action=null;animateEnemy(e,'Punch')}else animateEnemy(e,'Idle');}
for(const fx of effects){fx.life-=dt;if(fx.velocity){fx.m.position.addScaledVector(fx.velocity,dt);fx.velocity.y-=dt*8;fx.m.rotation.z+=dt*15}else if(!fx.m.isLine){fx.m.scale.setScalar(Math.max(.05,fx.life*5))}fx.m.material.opacity=Math.max(0,fx.life*4);if(fx.life<=0){fx.m.parent.remove(fx.m)}}effects=effects.filter(f=>f.life>0);
renderer.render(scene,camera)}
function jump(){if(playerY<=1.7){fallV=6.2}}
$('play').onclick=()=>{if($('overlay-title').textContent==='أكملت المئة جولة!'){round=1;hp=100;score=0;spawnRound(1)}else if(dead){hp=100;spawnRound(round)}else if(!enemies.length){let saved=1;try{saved=Number(localStorage.getItem('lasa-round'))||1}catch{}spawnRound(saved)}playing=true;dead=false;$('overlay').hidden=true;if(!mobile)renderer.domElement.requestPointerLock?.()};
addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.code==='Space'&&!e.repeat)jump();if(e.code==='KeyR'&&!e.repeat)reload()});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();if(!mobile&&playing){playing=false;$('overlay').hidden=false;$('overlay-title').textContent='متوقف مؤقتاً';$('play').textContent='تابع اللعب'}});document.addEventListener('pointerlockchange',()=>{if(!mobile&&!document.pointerLockElement&&playing){playing=false;$('overlay').hidden=false;$('overlay-title').textContent='متوقف مؤقتاً';$('play').textContent='تابع اللعب'}});
renderer.domElement.addEventListener('mousedown',e=>{if(e.button===0){keys.add('Mouse0');shoot()}});addEventListener('mouseup',()=>keys.delete('Mouse0'));addEventListener('mousemove',e=>{if(document.pointerLockElement===renderer.domElement){yaw-=e.movementX*.0022;pitch=THREE.MathUtils.clamp(pitch-e.movementY*.0022,-1.35,1.35);gunSwayX=THREE.MathUtils.clamp(gunSwayX+e.movementX*.04,-3,3);gunSwayY=THREE.MathUtils.clamp(gunSwayY+e.movementY*.04,-3,3)}});
renderer.domElement.addEventListener('pointerdown',e=>{if(!mobile||e.clientX<innerWidth*.35)return;look.id=e.pointerId;look.x=e.clientX;look.y=e.clientY;renderer.domElement.setPointerCapture(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(e.pointerId!==look.id)return;yaw-=(e.clientX-look.x)*.004;pitch=THREE.MathUtils.clamp(pitch-(e.clientY-look.y)*.004,-1.35,1.35);look.x=e.clientX;look.y=e.clientY});renderer.domElement.addEventListener('pointerup',e=>{if(look.id===e.pointerId)look.id=null});
const stick=$('joystick');function updateStick(e){const r=stick.getBoundingClientRect(),x=e.clientX-(r.left+r.width/2),y=e.clientY-(r.top+r.height/2),len=Math.max(1,Math.hypot(x,y));joystick.x=Math.max(-1,Math.min(1,x/48));joystick.y=Math.max(-1,Math.min(1,y/48));$('joystick-knob').style.transform=`translate(${x/len*Math.min(len,36)}px,${y/len*Math.min(len,36)}px)`}stick.addEventListener('pointerdown',e=>{stick.setPointerCapture(e.pointerId);joystick.id=e.pointerId;updateStick(e)});stick.addEventListener('pointermove',e=>{if(joystick.id===e.pointerId)updateStick(e)});for(const type of ['pointerup','pointercancel'])stick.addEventListener(type,e=>{if(joystick.id===e.pointerId){joystick.x=joystick.y=0;joystick.id=null;$('joystick-knob').style.transform=''}});
$('mobile-fire').addEventListener('pointerdown',e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);keys.add('Mouse0');shoot()});for(const type of ['pointerup','pointercancel','lostpointercapture'])$('mobile-fire').addEventListener(type,()=>keys.delete('Mouse0'));$('mobile-jump').onclick=jump;$('mobile-reload').onclick=reload;
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);mobile=matchMedia('(pointer:coarse)').matches});
requestAnimationFrame(loop);window.lasa={get state(){return{round,hp,ammo,remaining:enemies.filter(e=>!e.dead).length,gun:gun?.name,position:player.toArray(),playing}}};




